name: Database-Seeds CI/CD

on:
  push:
    branches:
      - "staging"
      - "release/*"
    paths:
      - "database-seeds/**"
      - "common/**"
  pull_request:
    branches:
      - "staging"
      - "release/*"
    paths:
      - "database-seeds/**"
      - "common/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      
      - name: Install dependencies
        run: pnpm --filter ./database-seeds/scripts --filter . install 

      - name: Run Tests
        run: pnpm --filter ./database-seeds/scripts test
        env:
          NODE_ENV: "test"

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
      - name: Sync Staging Database
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
        with:
          host: ${{ secrets.TACHI_HOST }}
          username: tachi
          key: ${{ secrets.TACHI_KEY }}
          script: tachi-database-sync -s

      - name: Sync Live Database
        if: startsWith(github.ref, 'refs/heads/release')
        uses: appleboy/ssh-action@1a8b3784eaa665f677fa114edd5683bb6a6bfaa8
        with:
          host: ${{ secrets.TACHI_HOST }}
          username: tachi
          key: ${{ secrets.TACHI_KEY }}
          script: tachi-database-sync
